services:
  - type: web
    name: finance-tracker-api
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/finance-tracker-0.0.1-SNAPSHOT.jar

databases:
  - name: finance-tracker-db
    databaseName: finance_tracker
    user: finance_tracker_user
    plan: free
