services:
  - type: web
    name: finance-tracker-api
    env: docker
    plan: free
    region: oregon
    rootDir: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JWT_SECRET
        value: "finance-tracker-jwt-secret-key-2024-super-secure-and-long-enough-for-production-use"
      - key: JWT_EXPIRATION
        value: 86400000
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: "admin123"
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/finance-tracker-0.0.1-SNAPSHOT.jar

  - type: web
    name: finance-tracker-frontend
    env: node
    plan: free
    region: oregon
    rootDir: ./frontend
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://finance-tracker-api.onrender.com/api

databases:
  - name: finance-tracker-db
    databaseName: finance_tracker
    user: finance_tracker_user
    plan: free
