spring:
  application:
    name: finance-tracker
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/finance_tracker}
    driver-class-name: org.postgresql.Driver
    # Simplified connection pool settings
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
      connection-test-query: SELECT 1
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure-in-production}
  expiration: ${JWT_EXPIRATION:86400000}

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# Logging - Focused debugging
logging:
  level:
    com.financeapp: DEBUG
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,https://perfin-roan.vercel.app,https://perfin-eu5o.onrender.com}