spring:
  application:
    name: finance-tracker
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/finance_tracker}
    username: ${DB_USERNAME:finance_tracker_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure-in-production}
  expiration: ${JWT_EXPIRATION:86400000}

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# Logging
logging:
  level:
    com.financeapp: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
