spring:
  application:
    name: finance-tracker
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/finance_tracker}
    driver-class-name: org.postgresql.Driver
    # Connection pool settings for better reliability
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 60000
      validation-timeout: 5000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 600000
      connection-test-query: SELECT 1
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure-in-production}
  expiration: ${JWT_EXPIRATION:86400000}

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# Logging - More verbose for debugging
logging:
  level:
    com.financeapp: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,https://perfin-roan.vercel.app,https://perfin-eu5o.onrender.com}